### ISSUE TITLE
support for windows and linux platform

### ISSUE THREAD

**Issue by mabDc** [xuelongqy/flutter_jscore#4]
近期会添加windows和linux平台支持吗？
我找到一个支持windows、linux、macos的JSC项目 [Lichtso/JSC-Standalone](https://github.com/Lichtso/JSC-Standalone)，它的[头文件](https://github.com/Lichtso/JSC-Standalone/tree/master/Windows/JSC/include)和 [flutter_jscore/lib/binding](https://github.com/xuelongqy/flutter_jscore/tree/master/lib/binding) 下声明一致，但是这个项目时间太古老，链接库是六年前的了，缺少一些方法。
如果coming soon还要等比较久的话，我准备用这个老版本先凑合用。

**Comment by xuelongqy** [comment]
其实可以把源码编译成对应平台的动态库即可，不过我最近没有时间。目前flutter的linux和windows还没有明确的可以版本

**Comment by mabDc** [comment]
我用了[Lichtso/JSC-Standalone](https://github.com/Lichtso/JSC-Standalone)编译的dll，修改了一些代码，在windows可以运行了。如下图：
![example](https://user-images.githubusercontent.com/19526331/89300818-5e625900-d69b-11ea-99c8-660d19ab10ad.png)
可惜由于dll比较老，js不支持ES6特性。希望作者有时间可以重新编译。

**Comment by xuelongqy** [comment]
苹果官方iTunes的Windows版本安装后有JavaScriptCore.dll，你试试看呢；Linux应该也有现成，我记得有一个专门管理js各种引擎的工具，忘记名字了，提取里面的so即可。如果成功了，麻烦帮忙打个补丁

**Comment by mabDc** [comment]
> 苹果官方iTunes的Windows版本安装后有JavaScriptCore.dll，你试试看呢；Linux应该也有现成，我记得有一个专门管理js各种引擎的工具，忘记名字了，提取里面的so即可。如果成功了，麻烦帮忙打个补丁

果然可以。安装[iTunes](https://www.apple.com/itunes/download/win64)提取jsc相关的dll文件（一共9个）就可以了。由于ffi在64位dart sdk里只能使用64位的dll，所以我只弄了64位的。

**Comment by xuelongqy** [comment]
v1.0.0已添加支持
